package eu.fbk.das.domainobject.core.entity.jaxb;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.09.01 at 03:11:28 PM CEST
//


import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragments specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="state" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://das.fbk.eu/Fragment}ServiceActionType">
 *                 &lt;attribute name="isInitial" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="action" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://das.fbk.eu/Fragment}ServiceActionType">
 *                 &lt;attribute name="actionType" use="required" type="{http://das.fbk.eu/Fragment}actionTypeValues" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transition" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="initialState" type="{http://das.fbk.eu/Fragment}ServiceStateType"/>
 *                   &lt;element name="finalState" type="{http://das.fbk.eu/Fragment}ServiceStateType"/>
 *                   &lt;element name="action">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://das.fbk.eu/Fragment}ServiceActionType">
 *                           &lt;attribute name="actionType" use="required" type="{http://das.fbk.eu/Fragment}actionTypeValues" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="consumerEntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "state",
        "action",
        "transition",
        "consumerEntityType"
})
@XmlRootElement(name = "fragment", namespace = "http://das.fbk.eu/Fragment")
public class Fragment {

    @XmlElement(namespace = "http://das.fbk.eu/Fragment", required = true)
    protected List<State> state;
    @XmlElement(namespace = "http://das.fbk.eu/Fragment", required = true)
    protected List<Action> action;
    @XmlElement(namespace = "http://das.fbk.eu/Fragment", required = true)
    protected List<Transition> transition;
    @XmlElement(namespace = "http://das.fbk.eu/Fragment", required = true)
    protected String consumerEntityType;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the state properties.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the state properties.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getState().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fragment.State }
     *
     *
     */
    public List<State> getState() {
        if (state == null) {
            state = new ArrayList<State>();
        }
        return this.state;
    }

    /**
     * Gets the value of the action properties.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the action properties.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAction().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fragment.Action }
     *
     *
     */
    public List<Action> getAction() {
        if (action == null) {
            action = new ArrayList<Action>();
        }
        return this.action;
    }

    /**
     * Gets the value of the transition properties.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transition properties.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransition().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fragment.Transition }
     *
     *
     */
    public List<Transition> getTransition() {
        if (transition == null) {
            transition = new ArrayList<Transition>();
        }
        return this.transition;
    }

    /**
     * Gets the value of the consumerEntityType properties.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getConsumerEntityType() {
        return consumerEntityType;
    }

    /**
     * Sets the value of the consumerEntityType properties.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setConsumerEntityType(String value) {
        this.consumerEntityType = value;
    }

    /**
     * Gets the value of the id properties.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id properties.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragments specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://das.fbk.eu/Fragment}ServiceActionType">
     *       &lt;attribute name="actionType" use="required" type="{http://das.fbk.eu/Fragment}actionTypeValues" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", namespace = "http://das.fbk.eu/Fragment")
    public static class Action
            extends ServiceActionType
    {

        @XmlAttribute(name = "actionType", required = true)
        protected ActionTypeValues actionType;

        /**
         * Gets the value of the actionType properties.
         *
         * @return
         *     possible object is
         *     {@link ActionTypeValues }
         *
         */
        public ActionTypeValues getActionType() {
            return actionType;
        }

        /**
         * Sets the value of the actionType properties.
         *
         * @param value
         *     allowed object is
         *     {@link ActionTypeValues }
         *
         */
        public void setActionType(ActionTypeValues value) {
            this.actionType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragments specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://das.fbk.eu/Fragment}ServiceActionType">
     *       &lt;attribute name="isInitial" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class State
            extends ServiceActionType
    {

        @XmlAttribute(name = "isInitial")
        protected Boolean isInitial;

        /**
         * Gets the value of the isInitial properties.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        public Boolean isIsInitial() {
            return isInitial;
        }

        /**
         * Sets the value of the isInitial properties.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setIsInitial(Boolean value) {
            this.isInitial = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragments specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="initialState" type="{http://das.fbk.eu/Fragment}ServiceStateType"/>
     *         &lt;element name="finalState" type="{http://das.fbk.eu/Fragment}ServiceStateType"/>
     *         &lt;element name="action">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://das.fbk.eu/Fragment}ServiceActionType">
     *                 &lt;attribute name="actionType" use="required" type="{http://das.fbk.eu/Fragment}actionTypeValues" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "initialState",
            "finalState",
            "action"
    })
    public static class Transition {

        @XmlElement(namespace = "http://das.fbk.eu/Fragment", required = true)
        protected ServiceStateType initialState;
        @XmlElement(namespace = "http://das.fbk.eu/Fragment", required = true)
        protected ServiceStateType finalState;
        @XmlElement(namespace = "http://das.fbk.eu/Fragment", required = true)
        protected Fragment.Transition.Action action;

        /**
         * Gets the value of the initialState properties.
         *
         * @return
         *     possible object is
         *     {@link ServiceStateType }
         *
         */
        public ServiceStateType getInitialState() {
            return initialState;
        }

        /**
         * Sets the value of the initialState properties.
         *
         * @param value
         *     allowed object is
         *     {@link ServiceStateType }
         *
         */
        public void setInitialState(ServiceStateType value) {
            this.initialState = value;
        }

        /**
         * Gets the value of the finalState properties.
         *
         * @return
         *     possible object is
         *     {@link ServiceStateType }
         *
         */
        public ServiceStateType getFinalState() {
            return finalState;
        }

        /**
         * Sets the value of the finalState properties.
         *
         * @param value
         *     allowed object is
         *     {@link ServiceStateType }
         *
         */
        public void setFinalState(ServiceStateType value) {
            this.finalState = value;
        }

        /**
         * Gets the value of the action properties.
         *
         * @return
         *     possible object is
         *     {@link Fragment.Transition.Action }
         *
         */
        public Fragment.Transition.Action getAction() {
            return action;
        }

        /**
         * Sets the value of the action properties.
         *
         * @param value
         *     allowed object is
         *     {@link Fragment.Transition.Action }
         *
         */
        public void setAction(Fragment.Transition.Action value) {
            this.action = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragments specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://das.fbk.eu/Fragment}ServiceActionType">
         *       &lt;attribute name="actionType" use="required" type="{http://das.fbk.eu/Fragment}actionTypeValues" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Action
                extends ServiceActionType
        {

            @XmlAttribute(name = "actionType", required = true)
            protected ActionTypeValues actionType;

            /**
             * Gets the value of the actionType properties.
             *
             * @return
             *     possible object is
             *     {@link ActionTypeValues }
             *
             */
            public ActionTypeValues getActionType() {
                return actionType;
            }

            /**
             * Sets the value of the actionType properties.
             *
             * @param value
             *     allowed object is
             *     {@link ActionTypeValues }
             *
             */
            public void setActionType(ActionTypeValues value) {
                this.actionType = value;
            }

        }

    }

}

