package eu.fbk.das.domainobject.core.entity.jaxb;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.10 at 10:04:59 AM CET
//



import eu.fbk.das.domainobject.core.entity.jaxb.activity.CompensationType;
import eu.fbk.das.domainobject.core.entity.jaxb.activity.EffectType;
import eu.fbk.das.domainobject.core.entity.jaxb.activity.PreconditionType;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ServiceActionType complex type.
 *
 * <p>The following schema fragments specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ServiceActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="receiveGoal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="goal" type="{http://das.fbk.eu/Annotation}GoalType"/>
 *         &lt;/choice>
 *         &lt;element name="precondition" type="{http://das.fbk.eu/Annotation}PreconditionType" minOccurs="0"/>
 *         &lt;element name="effect" type="{http://das.fbk.eu/Annotation}EffectType" minOccurs="0"/>
 *         &lt;element name="compensation" type="{http://das.fbk.eu/Annotation}CompensationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="receiveVar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceActionType", namespace = "http://das.fbk.eu/Fragment", propOrder = {
        "receiveGoal",
        "goal",
        "precondition",
        "effect",
        "compensation"
})
@XmlSeeAlso({
        Fragment.State.class,
        Fragment.Action.class,
        Fragment.Transition.Action.class
})
public class ServiceActionType {

    @XmlElement(namespace = "http://das.fbk.eu/Fragment")
    protected String receiveGoal;
    @XmlElement(namespace = "http://das.fbk.eu/Fragment")
    protected GoalType goal;
    @XmlElement(namespace = "http://das.fbk.eu/Fragment")
    protected PreconditionType precondition;
    @XmlElement(namespace = "http://das.fbk.eu/Fragment")
    protected EffectType effect;
    @XmlElement(namespace = "http://das.fbk.eu/Fragment")
    protected CompensationType compensation;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "receiveVar")
    protected String receiveVar;

    /**
     * Gets the value of the receiveGoal properties.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReceiveGoal() {
        return receiveGoal;
    }

    /**
     * Sets the value of the receiveGoal properties.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReceiveGoal(String value) {
        this.receiveGoal = value;
    }

    /**
     * Gets the value of the goal properties.
     *
     * @return
     *     possible object is
     *     {@link GoalType }
     *
     */
    public GoalType getGoal() {
        return goal;
    }

    /**
     * Sets the value of the goal properties.
     *
     * @param value
     *     allowed object is
     *     {@link GoalType }
     *
     */
    public void setGoal(GoalType value) {
        this.goal = value;
    }

    /**
     * Gets the value of the precondition properties.
     *
     * @return
     *     possible object is
     *     {@link PreconditionType }
     *
     */
    public PreconditionType getPrecondition() {
        return precondition;
    }

    /**
     * Sets the value of the precondition properties.
     *
     * @param value
     *     allowed object is
     *     {@link PreconditionType }
     *
     */
    public void setPrecondition(PreconditionType value) {
        this.precondition = value;
    }

    /**
     * Gets the value of the effect properties.
     *
     * @return
     *     possible object is
     *     {@link EffectType }
     *
     */
    public EffectType getEffect() {
        return effect;
    }

    /**
     * Sets the value of the effect properties.
     *
     * @param value
     *     allowed object is
     *     {@link EffectType }
     *
     */
    public void setEffect(EffectType value) {
        this.effect = value;
    }

    /**
     * Gets the value of the compensation properties.
     *
     * @return
     *     possible object is
     *     {@link CompensationType }
     *
     */
    public CompensationType getCompensation() {
        return compensation;
    }

    /**
     * Sets the value of the compensation properties.
     *
     * @param value
     *     allowed object is
     *     {@link CompensationType }
     *
     */
    public void setCompensation(CompensationType value) {
        this.compensation = value;
    }

    /**
     * Gets the value of the name properties.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name properties.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type properties.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type properties.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the receiveVar properties.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReceiveVar() {
        return receiveVar;
    }

    /**
     * Sets the value of the receiveVar properties.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReceiveVar(String value) {
        this.receiveVar = value;
    }

}

