//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.09.01 at 03:11:28 PM CEST
//

package eu.fbk.das.domainobject.core.entity.jaxb.activity;


import eu.fbk.das.domainobject.core.entity.jaxb.GoalType;

import javax.xml.bind.annotation.*;

/**
 *
 * Abstract activity to be refined by Adaptation Manager using its goal
 *
 *
 * <p>
 * Java class for abstractType complex type.
 *
 * <p>
 * The following schema fragments specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="abstractType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://das.fbk.eu/Process}activityType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="receiveGoal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="goal" type="{http://das.fbk.eu/Annotation}GoalType"/>
 *         &lt;/choice>
 *         &lt;element name="compensation" type="{http://das.fbk.eu/Annotation}CompensationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="receiveVar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstractType", propOrder = { "receiveGoal", "goal",
        "compensation" }, namespace = "http://das.fbk.eu/Process")
public class AbstractType extends ActivityType {

    protected String receiveGoal;
    @XmlElement(namespace = "http://das.fbk.eu/Process")
    protected GoalType goal;
    protected CompensationType compensation;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "receiveVar")
    protected String receiveVar;

    /**
     * Gets the value of the receiveGoal properties.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReceiveGoal() {
        return receiveGoal;
    }

    /**
     * Sets the value of the receiveGoal properties.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReceiveGoal(String value) {
        this.receiveGoal = value;
    }

    /**
     * Gets the value of the goal properties.
     *
     * @return possible object is {@link GoalType }
     *
     */
    public GoalType getGoal() {
        return goal;
    }

    /**
     * Sets the value of the goal properties.
     *
     * @param value
     *            allowed object is {@link GoalType }
     *
     */
    public void setGoal(GoalType value) {
        this.goal = value;
    }

    /**
     * Gets the value of the compensation properties.
     *
     * @return possible object is {@link CompensationType }
     *
     */
    public CompensationType getCompensation() {
        return compensation;
    }

    /**
     * Sets the value of the compensation properties.
     *
     * @param value
     *            allowed object is {@link CompensationType }
     *
     */
    public void setCompensation(CompensationType value) {
        this.compensation = value;
    }

    /**
     * Gets the value of the type properties.
     *
     * @return possible object is {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type properties.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the receiveVar properties.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReceiveVar() {
        return receiveVar;
    }

    /**
     * Sets the value of the receiveVar properties.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReceiveVar(String value) {
        this.receiveVar = value;
    }

}
