package eu.fbk.das.domainobject.core.entity.jaxb.activity;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.26 at 11:37:41 AM CET
//

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for onDPchangeType complex type.
 *
 * <p>The following schema fragments specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="onDPchangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="domainProperty" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="dp_name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "onDPchangeType", propOrder = {
        "domainProperty"
})
public class OnDPchangeType {

    @XmlElement(required = true)
    protected List<DomainProperty> domainProperty;

    /**
     * Gets the value of the domainProperty properties.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainProperty properties.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomainProperty().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnDPchangeType.DomainProperty }
     *
     *
     */
    public List<DomainProperty> getDomainProperty() {
        if (domainProperty == null) {
            domainProperty = new ArrayList<DomainProperty>();
        }
        return this.domainProperty;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragments specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="dp_name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "state"
    })
    public static class DomainProperty {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NMTOKEN")
        protected List<String> state;
        @XmlAttribute(name = "dp_name", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NMTOKEN")
        protected String dpName;

        /**
         * Gets the value of the state properties.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the state properties.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getState().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         */
        public List<String> getState() {
            if (state == null) {
                state = new ArrayList<String>();
            }
            return this.state;
        }

        /**
         * Gets the value of the dpName properties.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getDpName() {
            return dpName;
        }

        /**
         * Sets the value of the dpName properties.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setDpName(String value) {
            this.dpName = value;
        }

    }

}
